In [2]:
import numpy as np
import pandas as pd

CREATE DATAFRAME

In [3]:
data ={
    'name':['shivam','mishra','pathak','golu'],
    'AGE':[12,24,45,21],
    'CITY':['delhi','osai','palla','xyz'],
    'SALARY':[25555,34343,343432,54545]
}

In [4]:
df=pd.DataFrame(data)
df

     name  AGE   CITY  SALARY
0  shivam   12  delhi   25555
1  mishra   24   osai   34343
2  pathak   45  palla  343432
3    golu   21    xyz   54545

In [5]:
data_list =[
    ['joy',27,'paris',636363],
    ['luis',32,'usa',5656],
    ['fio',31,'america',8888],
    ['jio',76,'polo',41414]
]
df2 =pd.DataFrame(data_list)
# columns=['name','age','city','salary']
# df2=pd.DataFrame(data_list,columns=columns) #is wale me index nhai ha to index ke liye hamne column ka kaam kiya ha 
df2

      0   1        2       3
0   joy  27    paris  636363
1  luis  32      usa    5656
2   fio  31  america    8888
3   jio  76     polo   41414

In [6]:

columns=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

In [7]:
df

     name  AGE   CITY  SALARY
0  shivam   12  delhi   25555
1  mishra   24   osai   34343
2  pathak   45  palla  343432
3    golu   21    xyz   54545

In [8]:
df2

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

SELECTION AND INDEXING OF COLUMN

In [9]:
df2

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

In [10]:
df2['name']

0     joy
1    luis
2     fio
3     jio
Name: name, dtype: str

In [11]:
df2['city']

0      paris
1        usa
2    america
3       polo
Name: city, dtype: str

CREATING A COLUMN

In [12]:
df2['designation']=['doctor','engi','doctor','engineer']
df2

   name  age     city  salary designation
0   joy   27    paris  636363      doctor
1  luis   32      usa    5656        engi
2   fio   31  america    8888      doctor
3   jio   76     polo   41414    engineer

TEMPORARY DLT COLUMN

In [13]:
df2.drop('designation',axis=1)  #yaha par designation remove ho gaya but actual database me avu v ha it is only snapshot

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

In [14]:
df2 # here if we get the data of d2 yaha exist kr raha ha

   name  age     city  salary designation
0   joy   27    paris  636363      doctor
1  luis   32      usa    5656        engi
2   fio   31  america    8888      doctor
3   jio   76     polo   41414    engineer

PERMANENTLY DLT COLUMN

In [15]:
df2

   name  age     city  salary designation
0   joy   27    paris  636363      doctor
1  luis   32      usa    5656        engi
2   fio   31  america    8888      doctor
3   jio   76     polo   41414    engineer

In [16]:
df2.drop('designation',axis=1,inplace=True)

In [17]:
df2

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

delete multiple column

In [18]:
df2.drop(['city','salary'],axis=1) #temp hua h

   name  age
0   joy   27
1  luis   32
2   fio   31
3   jio   76

In [19]:
df2

   name  age     city  salary
0   joy   27    paris  636363
1  luis   32      usa    5656
2   fio   31  america    8888
3   jio   76     polo   41414

making a colmun

In [20]:
df2['designation']=['dr','eng','pilot','ai eng']

In [21]:
df2

   name  age     city  salary designation
0   joy   27    paris  636363          dr
1  luis   32      usa    5656         eng
2   fio   31  america    8888       pilot
3   jio   76     polo   41414      ai eng

making a multiple colmun

In [22]:
df2[['gender','experience']]=[['m',12],['m',3],['m',6],['m',7]]

In [23]:
df2

   name  age     city  salary designation gender experience
0   joy   27    paris  636363          dr      m         12
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

delete a row

In [29]:
df2.drop(0,axis=0) #ye temp hua ha

   name  age     city  salary designation gender experience
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

In [28]:
df2

   name  age     city  salary designation gender experience
0   joy   27    paris  636363          dr      m         12
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

In [30]:
df2.drop([0,1]) # we can provide axis 0 or not cozz in pandas default it set to the zero multiple row delete

  name  age     city  salary designation gender experience
2  fio   31  america    8888       pilot      m          6
3  jio   76     polo   41414      ai eng      m          7

In [31]:
df2

   name  age     city  salary designation gender experience
0   joy   27    paris  636363          dr      m         12
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

selecting a row

In [32]:
df2.loc[0] #loc means location

name              joy
age                27
city            paris
salary         636363
designation        dr
gender              m
experience         12
Name: 0, dtype: object

In [35]:
df2.loc[[0,1]] #multiple select a row

   name  age   city  salary designation gender experience
0   joy   27  paris  636363          dr      m         12
1  luis   32    usa    5656         eng      m          3

In [36]:
df2.iloc[0] #iloc means index location

name              joy
age                27
city            paris
salary         636363
designation        dr
gender              m
experience         12
Name: 0, dtype: object

SELECTIng suset of rows and columns

In [37]:
df2

   name  age     city  salary designation gender experience
0   joy   27    paris  636363          dr      m         12
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

In [38]:
df2.loc[[0,1]] [['city','salary']] #here i need only the city and salary

    city  salary
0  paris  636363
1    usa    5656

In [39]:
df2.loc[[2,3]] [['name','age']]

  name  age
2  fio   31
3  jio   76

conditional statements

In [53]:
df2

   name  age     city  salary designation gender experience
0   joy   27    paris  636363          dr      m         12
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

In [54]:
#whise age above 30

In [55]:
df2[df2['age']>30]

   name  age     city  salary designation gender experience
1  luis   32      usa    5656         eng      m          3
2   fio   31  america    8888       pilot      m          6
3   jio   76     polo   41414      ai eng      m          7

In [56]:
#whise age above 30 and from usa

In [65]:
df2[(df2['age']>30) & (df2['city']=='usa')]

   name  age city  salary designation gender experience
1  luis   32  usa    5656         eng      m          3

In [68]:
#whose salary 60k greater or age 20 city paris

In [72]:
df2[(df2['age']>20) & (df2['salary']>60000) &(df2['city']=='paris')]

  name  age   city  salary designation gender experience
0  joy   27  paris  636363          dr      m         12

In [75]:
df2[(df2['age']>30) & (df2['city']=='america') & (df2['designation']=='pilot') & (df2['salary']>100)]

  name  age     city  salary designation gender experience
2  fio   31  america    8888       pilot      m          6