In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

find missing data

In [13]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [15]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [16]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

removing missngdata

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.dropna() #works on the rows wise check each row and delete the row if there is an null value

     A  B    C    D
0  1.0  1  1.0  1.0

In [19]:
df.dropna(thresh=4) #itna not null value hona chy  usko rakhke delete kar dega

     A  B    C    D
0  1.0  1  1.0  1.0

In [20]:
df.dropna(thresh=3) #3 not null value ho usko rkhke delete kr dega sav

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [21]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

filling the missng data

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.fillna(0) #ye permanentlt nahi hua q ki inplace is equal true likhna hoga  jaha jaha vull hoga vaga 0 fill kardega df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [27]:
values={'A':0,'B':100,'C':200,'D':900}
df.fillna(value=values,inplace=True) #yaha par permanentlty data save ho gaya

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  900.0
2  0.0  3    3.0  900.0
3  4.0  4  200.0  900.0
4  5.0  5  200.0    5.0

In [28]:
df

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  900.0
2  0.0  3    3.0  900.0
3  4.0  4  200.0  900.0
4  5.0  5  200.0    5.0

In [29]:

df.fillna(df.mean())  #ye mean ke according data ko fill kar deta hai

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  900.0
2  0.0  3    3.0  900.0
3  4.0  4  200.0  900.0
4  5.0  5  200.0    5.0