In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [3]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
df1.shape

(5, 3)

In [6]:
df1.describe

<bound method NDFrame.describe of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [8]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [9]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

dataframe applying function

In [10]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [11]:
def square(x):
    return x**2

In [12]:
df1['B'].apply(square) #avi ye permaet ahu hua ha

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [14]:
df1['B']=df1['B'].apply(square)

In [15]:
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500